### ISSUE TITLE
Counter recipe can't work

### ISSUE THREAD

**Issue by packysauce** [micro-fan/aiozk#25]
https://github.com/tipsi/aiozk/blob/20e765fcf33ede1d25ac63bee74adb7259bbc75e/aiozk/recipes/counter.py#L29

Line 29 in `__init__` assumes that self.client is not None, but super() calls into Recipe, which sets self.client to None as the first order of business. the "recipes" proxy in the client does the right thing of call instantiate + call set_client, but you can't call set_client when calling Counter() always throws.

**Comment by packysauce** [comment]
ok, i dug into this. some notes:
the future creation thing can be straightened out by just moving the future creation into an overridden set_client method, nbd.
the watcher is configured *before* the paths are ensured/initialized, meaning that the rest of the code blows up because it was never initialized with an actual value, just null data (unhandled everywhere)
Counter isn't "thread" safe. You can't use multiple counter instances from the same ZKClient, and you can't use the same Counter in multiple coroutines. set_data's force parameter only uses the version from the stat_cache, which gets clobbered by other coroutines calling get_data on the newly changed value, so a force=False is always going to use a fresh version.
As it stands, ZKClient would need to change to make Counter useful.

That being said, I have a branch where I've fixed it enough to (maybe?) work in the 1 counter per client model, with a unit test and all that. I'm polishing it, but would love comments when I've submitted

**Comment by cybergrind** [comment]
Hi @packysauce ! Thank you for your contribution
I believe in general, you might want to use multiple counters in same ZKClient and share Counter in multiple coroutines. So if it doesn't allow to do that now, it needs to be fixed. I haven't checked stat_cache yet, but maybe we need to fix it too.
Will look on your branch when you submit it.
