### ISSUE TITLE
Remove loop argument

### ISSUE THREAD

**Issue by decaz** [micro-fan/aiozk#38]
To remove warning at latest Python version and to be ready for the future Python versions: `DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.`

**Comment by cybergrind** [comment]
Hey @decaz, not near PC now, it would be great if you add here exact places where we have this warning this will help to fix it faster.

**Comment by decaz** [comment]
@cybergrind I've created PR #39.
