### ISSUE TITLE
fan_wait command not found

### ISSUE THREAD

**Issue by rhdxmr** [micro-fan/aiozk#42]
When I run docker-compose up, this message is printed and aiozk_diag_1 container exited.

```
diag_1     | bash: fan_wait: command not found
aiozk_diag_1 exited with code 127

```

**Comment by cybergrind** [comment]
@rhdxmr, yeah, it was a package update and it should be fine if you re-build container with `docker-compose build`
If it not, do you mind to build container and check if you have it by path `/usr/local/bin/fan_wait`?

**Comment by rhdxmr** [comment]
@cybergrind docker-compose build solved the problem. thanks.
