### ISSUE TITLE
Connection issues handling

### ISSUE THREAD

**Issue by decaz** [micro-fan/aiozk#45]
Part of example client:
```python
while True:
    children = await client.get_children(path, watch=True)
    ...
    await client.wait_for_events([WatchEvent.CHILDREN_CHANGED], path)
```
1. Client 1 lost connection to the server
2. Client 2 added new children to the path
3. Client 1 repaired connection

In this case Client 1 doesn't get event so he won't continue the loop to the next iteration to update children list. Is there any proper way to handle such connection problems?

**Comment by cybergrind** [comment]
This should be handled in the watcher implementation https://github.com/micro-fan/aiozk/blob/master/aiozk/recipes/children_watcher.py But not all cases are covered in recipes tests, so it might not work.

If it isn't you can add test case for this case, it should be similar to https://github.com/micro-fan/aiozk/blob/master/aiozk/test/test_lock.py#L33

**Comment by decaz** [comment]
If I understand correct there should be some auxiliary task which handles connection losses and interacts with the main client loop. For instance:
```python
while True:
    await client.session.state.wait_for(States.SUSPENDED, States.LOST)
    ...
```
Am I right?

**Comment by cybergrind** [comment]
@decaz yes, you can use it, probably is better to have it implemented as 
```python
... asyncio.wait([watch_task, connection_lost], return_when=asyncio.FIRST_COMPLETED)
```
and then process response according to the fired event. 

But all this should be the part of Watcher and ideally, you don't need to implement it by hands every time

**Comment by decaz** [comment]
Ok, thanks!
