### ISSUE TITLE
Flaky barrier test

### ISSUE THREAD

**Issue by cybergrind** [micro-fan/aiozk#56]
https://travis-ci.org/github/micro-fan/aiozk/builds/678938631 -- Bad
https://travis-ci.org/github/micro-fan/aiozk/builds/678938764 -- Good

Code is the same

**Comment by cybergrind** [comment]
@rhdxmr could you please also look into that?

**Comment by rhdxmr** [comment]
@cybergrind OK I'm gonna find out what problem is.

**Comment by rhdxmr** [comment]
PR#58 is created for solving this issue.

**Comment by rhdxmr** [comment]
It is cleared. So I close this issue.
